"""
CARE-Paddy — Streamlit dashboard.

Demo script for Review-2:
  1. Field state panel  →  current conditions at a glance
  2. Recommendation card  →  action + plain-English reason + rule audit trail
  3. Forecast chart  →  median + 90% interval for t+1/2/3
  4. Break the sensor  →  inject fault, watch interval widen, watch gate fire
  5. SHAP  →  which features drove this specific forecast
  6. Validation results  →  LOSO error, calibration, gating curve

Run:
  streamlit run dashboard/app.py

The system banner is mandatory per the project honesty rules and must appear on every
view. Do not remove it. The exact wording is specified in AGENT_SPEC.md §8.
"""
from __future__ import annotations
import sys
from pathlib import Path
import numpy as np, pandas as pd
import streamlit as st
from xgboost import XGBRegressor

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import config as C
from decision import decide, ACTIONS
from features import FEATURES

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="CARE-Paddy",
    page_icon="🌾",
    layout="wide",
    initial_sidebar_state="expanded",
)

CFG = C.load()

# ── Mandatory honesty banner (AGENT_SPEC §8) ──────────────────────────────────
_BANNER = (
    "**Simulation result — not field-validated.** "
    "Field hydrology is generated by a physically-based water-balance model driven by "
    "{src} weather for {site}. "
    "The ML layer is a forecasting surrogate validated against that simulator, "
    "**not** against field observations. "
    "The ESP32 replaces the simulator without any change to the pipeline interface. "
    "No methane has been measured."
)

# ── Action colours ────────────────────────────────────────────────────────────
_ACTION_COLOUR = {
    "MAINTAIN": "#1d8348",
    "IRRIGATE": "#1a5276",
    "DELAY":    "#7d6608",
    "DRAIN":    "#922b21",
    "INSPECT":  "#784212",
}
_ACTION_ICON = {
    "MAINTAIN": "✅",
    "IRRIGATE": "💧",
    "DELAY":    "⏳",
    "DRAIN":    "🚿",
    "INSPECT":  "⚠️",
}

# ── Data / model loaders ──────────────────────────────────────────────────────
@st.cache_data
def load_features():
    return pd.read_parquet(ROOT / "data" / "processed" / "features.parquet")


@st.cache_data
def load_field_state():
    return pd.read_csv(ROOT / "data" / "processed" / "field_state.csv")


@st.cache_resource
def load_models():
    m = {}
    for h in CFG["model"]["horizons"]:
        for q in CFG["model"]["quantiles"]:
            k = int(q * 100)
            mdl = XGBRegressor()
            mdl.load_model(ROOT / "outputs" / "models" / f"xgb_h{h}_q{k:02d}.json")
            m[(h, k)] = mdl
    return m


df   = load_features()
fs   = load_field_state()
mdls = load_models()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Rice_field.jpg/320px-Rice_field.jpg",
             caption="Cauvery delta paddy field (illustrative)", use_container_width=True)
    st.header("🌱 Field selection")
    all_seasons = sorted(df.season_id.unique())
    season = st.selectbox("Season", all_seasons, index=len(all_seasons) - 1)
    S = df[df.season_id == season].dropna(subset=FEATURES).reset_index(drop=True)

    day = st.slider(
        "Day after transplanting",
        int(S.das.min()), int(S.das.max()), int(S.das.median()),
    )

    st.divider()
    st.header("🔧 Sensor fault injection")
    fault = st.radio(
        "Inject fault",
        ["none", "stuck water-level sensor", "drifting sensor", "erratic readings"],
        help="Break the sensor and watch the uncertainty gate refuse to actuate.",
    )
    st.caption(
        "This simulates the real failure modes the uncertainty gate is designed for. "
        "Sensor drift, stuck readings, and sudden noise all widen the 90% interval — "
        "the gate catches all three with a single threshold."
    )

    st.divider()
    st.header("⚙️ Gate calibration")
    gate_mode = st.radio(
        "Gate mode",
        ["Conformal (CQR)", "Fixed threshold"],
        help="Conformal: uses per-stage CQR-calibrated thresholds (novelty). "
             "Fixed: uses the slider value below.",
    )
    gate = st.slider(
        "Fixed gate threshold (mm)",
        10, 200,
        int(CFG["model"]["gate_interval_width_mm"]),
        5,
        help="Only used when gate mode is 'Fixed threshold'.",
    )

    st.divider()
    st.caption(f"Site: {CFG['site']['name']}")
    st.caption(f"Lat: {CFG['site']['lat']}  Lon: {CFG['site']['lon']}")

# ── Main area ─────────────────────────────────────────────────────────────────
st.title("🌾 CARE-Paddy — Stage-Aware, Uncertainty-Gated Irrigation Decision Support")

# Banner
row = S[S.das == day]
if row.empty:
    st.error("No data for this day. Try adjusting the slider.")
    st.stop()
row = row.iloc[0].copy()
wx_src = str(row.get("weather_source", "synthetic")).replace("_", " ")
st.warning(_BANNER.format(src=wx_src, site=CFG["site"]["name"]))

# ── Apply fault injection ─────────────────────────────────────────────────────
rng = np.random.default_rng(int(day))
if fault.startswith("stuck"):
    ref_val = float(S.wl_obs_mm.iloc[max(0, day - 7)])
    for c in ["wl_obs_mm", "wl_lag1", "wl_lag2", "wl_lag3", "wl_lag7"]:
        row[c] = ref_val
    row["wl_delta1"] = 0.0; row["wl_delta3"] = 0.0
elif fault.startswith("drift"):
    row["wl_obs_mm"] -= 80
    row["wl_delta1"] -= 20; row["wl_delta3"] -= 55
elif fault.startswith("erratic"):
    row["wl_obs_mm"] += float(rng.normal(0, 85))
    row["wl_delta1"] += float(rng.normal(0, 60))

# ── Load conformal thresholds ────────────────────────────────────────────────
conformal_thresholds = None
thresh_path = ROOT / "outputs" / "models" / "conformal_thresholds.csv"
if thresh_path.exists():
    _tdf = pd.read_csv(thresh_path)
    conformal_thresholds = dict(zip(_tdf.stage, _tdf.q_hat_mm))

# ── Run model ────────────────────────────────────────────────────────────────
X = pd.DataFrame([row[FEATURES].astype(float)])
fc = {
    h: {f"q{k:02d}": float(mdls[(h, k)].predict(X)[0]) for k in (5, 50, 95)}
    for h in CFG["model"]["horizons"]
}
fcd = {h: {"q05": v["q05"], "q50": v["q50"], "q95": v["q95"]} for h, v in fc.items()}

# Pass conformal thresholds only if conformal mode is selected
_ct = conformal_thresholds if gate_mode == "Conformal (CQR)" else None
d = decide(
    float(row.wl_obs_mm), str(row.stage), fcd,
    float(row.rain_fc_sum3_mm), CFG, gate_mm=float(gate),
    conformal_thresholds=_ct,
)

# ── KPI row ──────────────────────────────────────────────────────────────────
c1, c2, c3, c4, c5, c6 = st.columns(6)
c1.metric("Crop stage",       str(row.stage).replace("_", " ").title())
c2.metric("Day after transplanting", f"{int(row.das)}")
c3.metric("Water level",      f"{row.wl_obs_mm:.0f} mm",
          delta=f"{row.wl_delta1:.0f} mm/day" if abs(row.wl_delta1) > 0.5 else None)
c4.metric("Soil moisture",    f"{row.sm_obs_pct:.1f} %")
c5.metric("Rain forecast 3d", f"{row.rain_fc_sum3_mm:.0f} mm")
c6.metric("90% interval",     f"{d.interval_width_mm:.0f} mm",
          delta="GATED" if d.gated else "within threshold",
          delta_color="inverse" if d.gated else "normal")

# Show conformal info in a small metric if available
if conformal_thresholds and gate_mode == "Conformal (CQR)":
    q_hat = conformal_thresholds.get(str(row.stage),
                conformal_thresholds.get("_global", 0.0))
    st.caption(f"🔬 **Conformal gate active** — Stage Q̂ = {q_hat:.1f} mm "
               f"| Gate rule: `{d.rule}`")

# ── Recommendation card ───────────────────────────────────────────────────────
st.divider()
col_left, col_right = st.columns([1, 2])

with col_left:
    action_colour = _ACTION_COLOUR.get(d.action, "#555")
    action_icon   = _ACTION_ICON.get(d.action, "")
    st.markdown(
        f"""
        <div style="background:{action_colour};padding:24px;border-radius:12px;text-align:center;">
          <div style="font-size:2.8rem;">{action_icon}</div>
          <div style="color:white;font-size:2rem;font-weight:bold;margin:8px 0;">{d.action}</div>
          <div style="color:#ffffffcc;font-size:0.85rem;">{'UNCERTAINTY GATED' if d.gated else
               'CONSTRAINT APPLIED' if d.constraint_applied else
               f'Rule: {d.rule}'}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

with col_right:
    st.subheader("Decision reasoning")
    st.markdown(f"> {d.reason}")
    if d.constraint_applied:
        st.warning(
            "**Hard agronomic constraint applied:** Drainage is forbidden between "
            "panicle initiation and flowering, regardless of forecast. "
            "This constraint overrides any model output."
        )
    if d.gated:
        st.error(
            f"**Uncertainty gate fired:** The 90% prediction interval is "
            f"{d.interval_width_mm:.0f} mm, which exceeds the safety threshold of "
            f"{gate} mm. The system refuses to actuate and requests manual inspection."
        )
    # Stage context
    no_drain = str(row.stage) in CFG["phenology"]["no_drain_stages"]
    floor    = CFG["awd"]["stage_floor_mm"].get(str(row.stage), CFG["awd"]["safe_threshold_mm"])
    st.markdown(
        f"**Stage:** {row.stage.replace('_', ' ').title()}  |  "
        f"**AWD floor:** {floor:.0f} mm  |  "
        f"**Drain forbidden:** {'Yes ⚠️' if no_drain else 'No'}"
    )

# ── Forecast chart ────────────────────────────────────────────────────────────
st.divider()
st.subheader("Water level forecast — next 3 days")

forecast_df = pd.DataFrame({
    "Horizon":    [f"t+{h}" for h in fc],
    "5th pct":    [fc[h]["q05"] for h in fc],
    "Median":     [fc[h]["q50"] for h in fc],
    "95th pct":   [fc[h]["q95"] for h in fc],
    "Interval":   [fc[h]["q95"] - fc[h]["q05"] for h in fc],
}).set_index("Horizon")

col_chart, col_table = st.columns([3, 1])
with col_chart:
    st.line_chart(forecast_df[["5th pct", "Median", "95th pct"]])
with col_table:
    st.dataframe(forecast_df.round(1), use_container_width=True)

# Annotate floor and bund on the chart caption
fl_txt = f"Stage floor: {floor:.0f} mm | Bund height: {CFG['hydrology']['bund_height_mm']:.0f} mm"
st.caption(fl_txt + " | Positive = ponded; negative = water table below surface")

# ── Season trajectory ─────────────────────────────────────────────────────────
st.divider()
st.subheader("Season trajectory")
traj_tab, stage_tab = st.tabs(["Water level & rain", "Stage timeline"])

with traj_tab:
    hist = S[["das", "wl_obs_mm", "rain_mm", "et_demand"]].set_index("das")
    st.line_chart(hist)

with stage_tab:
    stage_df = S[["das", "stage", "kc", "cum_gdd", "gdd_fraction"]].copy()
    stage_df["stage_idx"] = stage_df["stage"].map(
        {s["name"]: i for i, s in enumerate(CFG["phenology"]["stages"])}
    )
    st.line_chart(stage_df.set_index("das")[["stage_idx", "kc"]])
    st.dataframe(
        stage_df.groupby("stage", observed=True)["das"].agg(["min", "max"])
                .rename(columns={"min": "day_start", "max": "day_end"}),
        use_container_width=True,
    )

# ── SHAP explainability ───────────────────────────────────────────────────────
st.divider()
with st.expander("Feature attribution (TreeSHAP)", expanded=False):
    col_bs, col_wf = st.columns(2)
    for col, fname, cap in [
        (col_bs, "shap_beeswarm.png", "Global feature importance (all seasons)"),
        (col_wf, "shap_waterfall.png", "Single-decision waterfall (driest day)"),
    ]:
        p = ROOT / "outputs" / "figures" / fname
        with col:
            if p.exists():
                st.image(str(p), caption=cap, use_container_width=True)
            else:
                st.caption(f"Run `python src/explain.py` to generate {fname}")
    st.caption(
        "SHAP is **feature attribution**, not causal inference. "
        "It shows which inputs moved this specific forecast relative to the baseline — "
        "it does not imply that changing those inputs *causes* the water level to change."
    )

# ── Validation results ────────────────────────────────────────────────────────
st.divider()
with st.expander("Validation results", expanded=False):
    tabs = st.tabs([
        "Model comparison",
        "Interval calibration",
        "Gating curve",
        "Stage false-actuation",
        "Gating summary",
        "Conformal calibration (CQR)",
    ])
    file_map = [
        ("model_comparison.csv",
         "Leave-one-season-out MAE/RMSE/R² (simulation result). "
         "Wu et al. 2023 used a random 7:3 split — we use LOSO to prevent temporal leakage."),
        ("interval_coverage.csv",
         "Does the nominal 90% interval actually contain 90% of observed values? "
         "Includes both raw quantile and CQR-adjusted coverage."),
        ("gating_curve.csv",
         "False-actuation rate vs deferral fraction. If gating works, the curve falls."),
        ("stage_false_actuation.csv",
         "False actuation and deferral rate broken down by crop stage."),
        ("gating_summary.csv",
         "Summary: false actuation with and without the uncertainty gate."),
        ("conformal_coverage_by_stage.csv",
         "Conformalized Quantile Regression (CQR) per-stage coverage and interval width. "
         "The key result: CQR guarantees ≥90% coverage per stage, unlike raw quantile regression."),
    ]
    for tab, (fname, caption) in zip(tabs, file_map):
        with tab:
            p = ROOT / "outputs" / "metrics" / fname
            if p.exists():
                st.caption(caption)
                st.dataframe(pd.read_csv(p), use_container_width=True)
                # Show key figures for model_comparison
                if fname == "model_comparison.csv":
                    for fig_name in ["model_comparison.png", "gating_curve.png",
                                     "interval_coverage.png", "uncertainty_by_stage.png"]:
                        fp = ROOT / "outputs" / "figures" / fig_name
                        if fp.exists():
                            st.image(str(fp), use_container_width=True)
            else:
                st.caption(f"Run `python run_all.py` to generate {fname}.")

    # Extra figures for the conformal tab
    with tabs[5]:  # Conformal calibration tab
        # Show conformal thresholds
        ct_path = ROOT / "outputs" / "metrics" / "conformal_thresholds.csv"
        if ct_path.exists():
            st.subheader("Per-stage conformal thresholds (Q̂)")
            st.caption(
                "Q̂ is the conformal correction in mm. Positive Q̂ means the raw quantile "
                "interval is too narrow and needs widening. Larger Q̂ = more conservative gate."
            )
            st.dataframe(pd.read_csv(ct_path), use_container_width=True)

        # Show conformal vs fixed gate comparison
        for fig_name, cap in [
            ("conformal_vs_fixed_gate.png",
             "Per-stage comparison of false actuation and deferral rates: Fixed vs Conformal (CQR) gate"),
            ("conformal_coverage_by_stage.png",
             "Per-stage interval coverage: raw quantile vs CQR-adjusted (h=3). "
             "CQR guarantees ≥90% coverage per stage."),
        ]:
            fp = ROOT / "outputs" / "figures" / fig_name
            if fp.exists():
                st.image(str(fp), caption=cap, use_container_width=True)

        # Show conformal summary
        cs_path = ROOT / "outputs" / "metrics" / "conformal_summary.csv"
        if cs_path.exists():
            st.subheader("Conformal vs Fixed gate summary")
            st.dataframe(pd.read_csv(cs_path, index_col=0).T, use_container_width=True)

        cvf_path = ROOT / "outputs" / "metrics" / "conformal_vs_fixed_stage.csv"
        if cvf_path.exists():
            st.subheader("Per-stage false actuation: Fixed vs Conformal")
            st.dataframe(pd.read_csv(cvf_path), use_container_width=True)

# ── Sensitivity analysis ──────────────────────────────────────────────────────
with st.expander("Sensitivity analysis (±30% perturbation)", expanded=False):
    st.markdown(
        "Key parameters (percolation rate and crop Kc) are not measured at this specific "
        "field — they are sourced from SoilGrids and FAO-56. This analysis shows that "
        "model ranking and policy behaviour are stable under ±30% perturbation of those "
        "parameters, so the conclusions are not artefacts of parameter choices."
    )
    for fig_name in ["sensitivity_xgboost.png", "sensitivity_persistence.png"]:
        fp = ROOT / "outputs" / "figures" / fig_name
        if fp.exists():
            st.image(str(fp), use_container_width=True)
        else:
            st.caption(f"Run `python src/sensitivity.py` to generate {fig_name}.")
    sa_path = ROOT / "outputs" / "metrics" / "sensitivity_analysis.csv"
    if sa_path.exists():
        st.dataframe(pd.read_csv(sa_path), use_container_width=True)

# ── System architecture diagram ───────────────────────────────────────────────
with st.expander("System architecture", expanded=False):
    st.markdown("""
```
SENSING          ESP32: water level, soil moisture, air temp/humidity
   |
CONTEXT          NASA POWER (historical) + Open-Meteo (forecast) + Sentinel-1 (Review-3)
   |
PHENOLOGY        Cumulative GDD → crop stage        [rule-based, not ML]
   |
FORECAST         Quantile XGBoost → water level at t+1/t+2/t+3  (5th/50th/95th percentiles)
   |
DECISION + GATE  Hard constraint → uncertainty gate → thresholds → action
   |
ACTUATION        Pump/valve relay  OR  recommendation only
   |
FEEDBACK         Back to the field
```

**Hard constraint** (step 1): drainage forbidden between panicle initiation and flowering.  
**Uncertainty gate** (step 2): if the 90% interval exceeds the gate threshold, issue INSPECT.  
**Thresholds** (step 3): stage-dependent AWD floor — act on *approach*, not after breach.
    """)

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.caption(
    "CARE-Paddy · B.Tech Capstone · "
    f"Weather: {wx_src} · "
    "References: Wu et al. (2023), Ma et al. (2025), Ouyang et al. (2023), "
    "Menefee et al. (2023), FAO-56, SoilGrids Hengl et al. (2017)"
)
